### ISSUE TITLE
New Carla Map Town01

### ISSUE THREAD

**Issue by Cyrus-k** [MaisJamal/Carla_Towns-Apollo_maps#5] opened 2023-10-17 07:59 UTC
Hello, developers. 
I am glad to tell you that I have finished adding all the signals to the base_map and till now it works well on my machine. The way I determined the overlap start_s and end_s is not quite same as you. I use the Apollo's script add_signal.py to get the overlap info for each signal and that makes the overlap info I added is different from yours. However, It works fine for me. I can send my modified map to you and you may check the correctness of it. Just let me know and i will send it via email.
By the way, did u find the co-simulation would be a little stuck if running the co-simulation for some time? As for me, the stuck will cause the ego-car may hit something it shouldn't hit like road edges or  it may ignore the traffic light signal. I wonder whether it is the machine's problem or other hidden problem.

**Comment by MaisJamal** [comment] 2023-10-17 08:38
Thanks for your efforts. You can send the modified map, or make a pull request. 
Regarding the stuck, it is probably related to a limitation of your resources (CPU,GPU,RAM,..). Try monitoring RAM and CPU to check if they hit the maximum. If you have access to another computer, consider running Carla simulator on one computer, and Apollo and the bridge on the other. The connection can be done through SSH. 
This would make the simulation run better.

**Comment by MaisJamal** [comment] 2023-10-17 09:19
I have checked your modified map, the overlaps of the added signals should be adjusted. The start of the overlap with the lane near the signal affects the position of the stop decision.
Please note, this picture is of a signal that you added automatically (overlap was not adjusted), here you can see the stop position of the ego on the lane:
![not_adjusted_overlap](https://github.com/MaisJamal/Carla_apollo_maps/assets/17913075/d9df9b61-8fab-4bb7-8fd3-9e0e9294f730)
when running with a simulator with traffic, this will cause the ego to pass the intersection even when the signal is on red.

while here you can see the stop position is posed near the white line correctly, because I have adjusted the overlap:
![adjusted_overlap](https://github.com/MaisJamal/Carla_apollo_maps/assets/17913075/0eef6c3b-f38d-4e38-bc8c-c911cae7545b)

To fix this issue for each signal, you need to fix the start s, and end s of the overlap with the near lane, defined in the picture:
![overlap_s](https://github.com/MaisJamal/Carla_apollo_maps/assets/17913075/c42c5e9a-32b4-4a04-b3c4-eae9409f10ef)
What I usually do is 
- send a routing request as in the picture, 
- monitor the channel /apollo/routing_request to define start s and end s, making sure that they are on the same lane,
- add 0.5 (for example) to the end s value, to make sure that it covers the end of the lane.

**Comment by Cyrus-k** [comment] 2023-10-17 09:35
Can you tell me where your start and destination is? As I saw in this picture, the ego car is running on the lane 3_1_1. So I run the co-simulation by myself. And It seems different from yours. It looks like below.
![Screenshot from 2023-10-17 17-28-06](https://github.com/MaisJamal/Carla_apollo_maps/assets/55689315/91a866d9-ab8b-4588-b9de-a399cdc8ecc9)
It can stop correctly before the signal. So can you give me your start and destination point, so I can reproduce your case.

**Comment by MaisJamal** [comment] 2023-10-17 09:47
I monitored this issue in all added signals except for signal20. You can test it in Simcontrol without Carla simulator.
Example routing request for producing the issue;
first point(x,y): (92.45, -161.86) , 
second point(x,y): (92.35,-107.61).

**Comment by Cyrus-k** [comment] 2023-10-17 10:15
Sorry to disturb you. I would like to know if there is difference between testing in Apollo simcontrol and testing with carla.
I seldom use Simcontrol and I wonder if you don't use carla simulator how can you make the traffic light work in dreamview? I use simcontrol just now and i found traffic lights don't work. But even that time, I still found ego-car stopping right before the traffic light.
Thank you for your instructions.

**Comment by MaisJamal** [comment] 2023-10-17 10:33
You can make the traffic lights work by running the script ./scripts/manual_light.sh , then you can switch the light of the signal manually by this script.
The difference between Simcontrol and running with a simulator like Carla:
In Simcontrol mode, the ego vehicle follows the planned trajectory ideally (with no control and no feedback from a car model). While, when you run Apollo with Carla, you will have feedback from Carla regarding chassis and location of the vehicle, then Apollo control will send throttle,brake, and steering commands to control the vehicle to follow the planned trajectory. Running with a simulator is closer to reality.On the other hand, running in Simcontrol is simple and can be a pre-step, for example, when you debug or try to solve some issue, you can run it in simcontrol to simplify the experiment and narrow down the possible causes of the issue to Apollo's planning module or Apollo's map.
For experimenting, of course the scenario should be run with a simulator like Carla. I use Simcontrol only for checking some problem quickly.
Have you managed to reproduce the issue of ego passing the stop line?

**Comment by Cyrus-k** [comment] 2023-10-17 10:55
Thank I got it. But unfortunately, I still cannot reproduce the issue of ego passing the stop line.
I have tried your case and I also ran some cases by myself, but I still cannot reproduce the issue.
Here are some printscreens:
![Screenshot from 2023-10-17 18-50-05](https://github.com/MaisJamal/Carla_apollo_maps/assets/55689315/2032ee46-df32-436d-afff-39aac39624a5)
![Screenshot from 2023-10-17 18-50-33](https://github.com/MaisJamal/Carla_apollo_maps/assets/55689315/9e3e4094-f8fd-495b-a321-35ed7cd66159)
As you can see in the picture, the car always stop correctly before the stop line, which is different from yours.
I think there must be some mismatches between maps we use. I will send you my map again via email.

**Comment by MaisJamal** [comment] 2023-10-17 11:12
Can you please test it with Carla also?

**Comment by Cyrus-k** [comment] 2023-10-17 12:48
Of course. I have already tested with carla. I can send my test video to you via email.

**Comment by MaisJamal** [comment] 2023-10-17 15:09
That's great. Thanks for editing the map. I have updated the map in this repo, and updated the [Carla_Apollo_bridge](https://github.com/MaisJamal/carla_apollo_bridge). The bridge now publishes the ground truth of all traffic lights in Town01.
I will close the issue, as we have successfully updated the map.

**Closed as completed by MaisJamal** 2023-10-17 15:09 UTC
